@startuml
class App{
    App myApp
    JSONParser jParser
    String outcome
    String product name

    + productName()
}

class JSONParser{
    + jsonReader(productName)
    - getProductPrice(productJsonObject)
    - getProductQuantity(productJsonObject)
    - ifEqual(productName, productJsonObject)
    + notEqual()
}

App <|-- JSONParser

@enduml