@startuml
class App{
    BuildParagraph paragraphBuilder
    WordFinder finder
    GenerateOutput output

    String infile
    ArrayList<String> paragraph
}

class BuildParagraph {
    + readFile(infile)
    + addword(word, paragraph)
}

class WordFinder{
    + modifyList(paragraph)
    + utilizeToUse(paragraph, i)
}

class GenerateOutput{
    - Scanner

    + createOutputString(paragraph)
    + getOutfile()
    + toOutfile(output, outfile)
}

App o--> BuildParagraph
BuildParagraph -|> WordFinder
WordFinder -> GenerateOutput
App <|- GenerateOutput

@enduml