@startuml
class App{
    String website
    String author

    + readInput()
}

class CreateFile {
    + userYesOrNo()
    + generateNewFile(yesOrNo, name)

    + createJavaScriptFile(name)
    + createCSSFile(Name)
}

class CreateLink {
    + generateLink(name)
}

class GenerateOutput {
    + output(outputString)

    + createdHTMLFile(website, html)
    + createdFolder(website, websiteType)
}

App <|-- CreateFile
CreateFile <|-- CreateLink
App o--> GenerateOutput
@enduml