@startuml

class Application {
    CreateList list
    FindUniqueWords uniqueWords
    FindFrequency freq
    GenerateOutput genOutput

    String fileName

    ArrayList<String> allWords
    ArrayList<String> unique
    Integer[] frequency

}

class CreateList{
    + readFile(fileName)
    + addToList(in, words)
}

class FindUniqueWords {
    + uniqueWords(allWords)
    + isUnique(curWord, uniqueWords)
}

class FindFrequency {
    + findFrequency(allWords, uniqueWords)
    + frequency(allWords, findFreq)
}


class GenerateOutput {
    + OutputString(unique, freqs)
    + generateStars(numStars)
    + checkIfValid(numStars)
    + testNull(stars)
}

Application <|-- CreateList
CreateList o-> FindUniqueWords
CreateList o-> FindFrequency
Application o-> GenerateOutput

@enduml